### ISSUE TITLE
Podpora pro LVGL

### ISSUE THREAD

**Issue by maxbrito500** [colesnicov/ccript#2]
Dobrý den,

bylo by možné mít podporu pro LVGL 8.x funkce, které mají být volány ze skriptu? Chtěl bych použít váš projekt pro interpretaci souborů C, ale potřebujeme tento druh rozhraní, aby fungoval.

Děkuji moc!

**Comment by colesnicov** [comment]
Ahoj. Moc me tesi ze mate zajem o vyzkouseni teto knihovny.  Napisu rovnou na rovinu, jsem sam na vyvoj HW i SW, takze moc casu na opravy chyb nemam. Ale urcite by se mela dat navesit funkce ktera bude volat api LVGL. V pocitaci mam novejsi verzi s jiz opravenymi nekolika chyby. Behem zvatku ji zreviduji a nahraji na GIT. Oznamim vam to tady. Jinak rad poradim, rad vnesu pripadne/uzitecne zmeny a budu rad za otestovani a pripominky.

**Comment by colesnicov** [comment]
Take co se tyce toho odstavce v popisu "_ccript je napsan na cistem 'C' bez vnejsich zavislosti._ " tak **to neni uplna pravda**. Je zavisla na https://github.com/colesnicov/cvector coz je **dynamicky kontejner pro promenne a funkce**. Dale je zavisla na https://github.com/colesnicov/filebuffer ktery **umoznuje cist soubor po castech a nezahltit tim HEAP** a je take zavisla na https://github.com/colesnicov/emblib kde potrebuje funkce `itoa` a podobne, jejichz implementaci v mem ESP8266-RTOS-SDK jsem nenasel (myslim).

**Comment by colesnicov** [comment]
A take neinterpretuje jazyk 'C' jen pouziva podobnou syntaxi.V podstate se jedna o parser/lexer ktery na zaklade klicovych slov a navesenych na ne funkci te funkce vola. Jednoduche, uzitecne, funkcni. Pouzivam to na Wemos D1 kde mi v oddelenem Tasku bezi tento praser, ceka ve fronte az dostane nazev souboru ktery ma spustit a ten pak zpracuje:

```
while(1){
    char filename[50] = {'\0'};
    if(xQueueReceive(&filename, 10)){
        var_s *var = cc_parse(&parser, filename, NULL, 0);
        cc_varDestroy(var);
    }
}
```

**Comment by colesnicov** [comment]
Uz jste to zkouseli? Nahral jsem posledni co mam v pocitaci, odzkouseno jak na ESP tak na PC. Dokumentace neni uplna, tak se kouknete do example jak se inicializuje a do cc_configs.h co se nastavuje. V pripade ze pouzivate ESP-IDF tak se nastavuje pres `make menuconfig` v sekci `components/ccript`

**Comment by colesnicov** [comment]
Mozna by jste se mohl podivat tady https://gitlab.com/zsaleeba/picoc
